# Generated by Django 3.0 on 2019-12-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20191205_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='estado',
        ),
    ]
